config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'books#index'
  resources :users, only: :show

  resources :rooms, only: [:new, :create, :destroy] do
    resources :talks, only: [:index, :create]
  end
  resources :books do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre
  belongs_to :user
  has_many :comments, dependent: :destroy

  with_options presence:true do
    validates :title
    validates :author
    validates :description
    validates :genre_id, numericality: { other_than: 1}
  end

  has_one_attached :image
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :text, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '文学・評論' },
    { id: 3, name: 'ノンフィクション' },
    { id: 4, name: 'ビジネス・経済' },
    { id: 5, name: '歴史・地理' },
    { id: 6, name: '政治・社会' },
    { id: 7, name: '芸能・エンターテインメント' },
    { id: 8, name: 'アート・建築・デザイン' },
    { id: 9, name: '人文・思想・宗教' },
    { id: 10, name: '暮らし・健康・料理' },
    { id: 11, name: 'サイエンス・テクノロジー' },
    { id: 12, name: '趣味・実用' },
    { id: 13, name: '教育・自己啓発' },
    { id: 14, name: 'スポーツ・アウトドア' },
    { id: 15, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :books
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :talks, dependent: :destroy
  
  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/talk.rb
class Talk < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :talking, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :comments
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :talks

  with_options presence: true do
    validates :nickname
    validates :profile
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!, except: [:index]
  before_action :set_book, only: [:show, :edit, :destroy, :update]
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @book.comments.includes(:user)
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre_id, :description, :image).merge(user_id: current_user.id)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      redirect_to book_path(@comment.book)
    else
      @book = @comment.book
      @comments = @book.comments
      render "books/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, book_id: params[:book_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
      if @room.save
        redirect_to root_path
      else
        render :new
      end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to root_path
  end

  private
  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController

  def index
    @talk = Talk.new
    @room = Room.find(params[:room_id])
    @talks = @room.talks.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @talk = @room.talks.new(talk_params)
      if @talk.save
        redirect_to room_talks_path(@room)
      else
        @talks = @room.talks.includes(:user)
        render :index
      end
  end

  private

  def talk_params
    params.require(:talk).permit(:talking).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
    <%= render "devise/shared/header" %>

    <div class="form_wrapper">
      <div class="book-main">
          <h1 class="book-title">本の投稿</h1>

            <%= form_with model: @book, local: true do |f| %>
            
            <div class="image-upload">
             <div class="image-text">
              投稿画像
              <span class="indispensable">必須</span>
             </div>
            <div class="click-upload">
              <%= f.file_field :image, id:"item-image" %>
             </div>

            <div class="new-book">
              <div class="book-name">
                題名
                <span class="indispensable">必須</span>
              </div>
              <%= f.text_area :title, class:"book-text",  placeholder:"本のタイトルの記入" %>
            </div>

            <div class="new-book">
              <div class="book-name">
                著者
                <span class="indispensable">必須</span>
              </div>
              <%= f.text_area :author, class:"book-text",  placeholder:"本の著者の記入" %>
            </div>

            <div class="new-book">
              <div class="book-name">
                カテゴリー
                <span class="indispensable">必須</span>
              </div>
              <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, 
              {class: "select_box", id:"item-shipping-fee-status"}) %>
            </div>

            <div class="new-book">
              <div class="book-explain">
                <div class="book-explanation">
                  商品の説明
                  <span class="indispensable">必須</span>
                </div>
                <%= f.text_area :description, class:"items-text", placeholder:"本の説明（必須 300文字まで）（読んだ感想・オススメな箇所など）" ,rows:"7" ,maxlength:"３00" %>
              </div>
            </div>

             <div class="sell-btn-contents">
              <%= f.submit "投稿する" ,class:"sell-btn" %>
              <%=link_to 'もどる', book_path(@book.id), class:"back-btn" %>
             </div>
            <% end %>
      </div>
    </div>

    <%= render "devise/shared/footer"%>

app/views/books/index.html.erb
<%= render "devise/shared/header" %>

<div class="wrapper">
  <div class="side-bar">
    <div class="side-bar-header">
       <div class="header-name">
          <% if user_signed_in?%>
          <%= link_to current_user.nickname, user_path(current_user.id)%>
          <% end %>
       </div>
       <% if user_signed_in?%>
       <div class="create-room">
         <%=  link_to 'roomを作成する', new_room_path %>
       </div>
       <% end %>
    </div>
    <div class="rooms">
      <% if user_signed_in?%>
      <% current_user.rooms.each do |room|%>
       <div class="room">
         <div class="room-name">
          <%=  link_to room.name, room_talks_path(room.id) %>
         </div>
       </div>
       <% end %>
       <% end %>
    </div>
  </div>




  <div class="main-bar">
    <div class="main-header">
      <% if user_signed_in?%>
        <div class="greeting">
          ようこそ、
          <%= link_to "#{current_user.nickname}さん",user_path(current_user.id), class: :greeting_link %>
        </div>
      <% end %>
    </div>

   <div class='main-book'>
    <h2 class='main-book-title'>本の一覧紹介</h2>
    <ul class='book-lists'>

      <% @books.each do |book| %>
      <li class='list'>
        <%= link_to book_path(book.id)  do %>
        <div class='book-img-view'>
          <%= image_tag book.image.variant(resize: '250x300'), class: "book_image" %>

          <div class='book-information'>
            <div class='book-nickname'>
              <span>タイトル<br> <%= book.title %><br> ジャンル<br>  <%= book.genre.name%></span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
  </div>
</div>


<%= render "devise/shared/footer"%>

app/views/books/new.html.erb
    <%= render "devise/shared/header" %>
    
    <div class="form_wrapper">
      <div class="book-main">
          <h1 class="book-title">本の投稿</h1>

            <%= form_with model: @book, local: true do |f| %>
            
            <div class="image-upload">
             <div class="image-text">
              投稿画像
              <span class="indispensable">必須</span>
             </div>
            <div class="click-upload">
              <%= f.file_field :image, id:"item-image" %>
             </div>

            <div class="new-book">
              <div class="book-name">
                題名
                <span class="indispensable">必須</span>
              </div>
              <%= f.text_area :title, class:"book-text",  placeholder:"本のタイトルの記入" %>
            </div>

            <div class="new-book">
              <div class="book-name">
                著者
                <span class="indispensable">必須</span>
              </div>
              <%= f.text_area :author, class:"book-text",  placeholder:"本の著者の記入" %>
            </div>

            <div class="new-book">
              <div class="book-name">
                カテゴリー
                <span class="indispensable">必須</span>
              </div>
              <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, 
              {class: "select_box", id:"item-shipping-fee-status"}) %>
            </div>

            <div class="new-book">
              <div class="book-explain">
                <div class="book-explanation">
                  商品の説明
                  <span class="indispensable">必須</span>
                </div>
                <%= f.text_area :description, class:"items-text", placeholder:"本の説明（必須 300文字まで）（読んだ感想・オススメな箇所など）" ,rows:"7" ,maxlength:"３00" %>
              </div>
            </div>

             <div class="sell-btn-contents">
              <%= f.submit "投稿する" ,class:"sell-btn" %>
              <%=link_to 'もどる', root_path, class:"back-btn" %>
             </div>
            <% end %>
      </div>
    </div>

    <%= render "devise/shared/footer"%>

app/views/books/show.html.erb
<%= render "devise/shared/header" %>

<div class="form_show_wrapper">
  <div class="book-show-form">
    <div class="book-show">
        <h1 class="book_hedding">
          <%= @book.title %>
        </h1>
        <%= link_to @book.user.nickname, "hoge", class: :book__user %>
        <% if user_signed_in? && current_user.id == @book.user_id %>
          <div class="prototype__manage">
            <%= link_to "編集する", edit_book_path(@book.id), class: :book__btn %>
            <%= link_to "削除する", book_path(@book.id), method: :delete, class: :book__btn %>
          </div>
        <% end %>
        
        <div class="image-text">
          <%= image_tag @book.image,  class: :book__image %>
        </div>

        <div class="new-book">
          <div class="book-name">
            著者
          </div>
          <%= @book.author %>
        </div>

        <div class="new-book">
          <div class="book-name">
            カテゴリー
          </div>
          <%= @book.genre.name %>
        </div>

        <div class="new-book">
          <div class="book-name">
            商品の説明
          </div>
          <%= @book.description %>
        </div>


        <div class="books_comments">
          <% if user_signed_in? %>
            <%= form_with(model: [@book, @comment], local: true) do |f| %>
              <div class="field">
                <%= f.label :text, "コメント" %><br />
                <%= f.text_field :text %>
              </div>
              <div class="actions">
                <%= f.submit "送信する", class: :show_form_btn %>
              </div>
            <% end %> 
          <% end %>
          <h4> コメント一覧</h4>
          <ul class="comments_lists">
            <% @comments.each do |comment| %>
              <li class="comments_list">
                <%= link_to comment.user.nickname, "hoge", class: :comment_user %>
                 <%=  comment.text %>
              </li>
            <% end %>
          </ul>
        </div>
    </div>
  </div>
</div>

<%= render "devise/shared/footer"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookcafe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/new.html.erb
<%= render "devise/shared/header"%>

<div class="wrapper">
  <div class="book-room">
    <h1>新規ルーム</h1>
    <%=form_with model: @room, local: true do |f|%>
      <div class="book-form-field">
        <div class="book-form-field-left">
          <%= f.label :ルーム名, class: "book-form-field-left-label"%>
        </div>
        <div class="book-form-field-right">
          <%= f.text_field :name, class: "book-form-field-name", placeholder: 'ルーム名を入力してください'%>
        </div>
      </div>
      <div class="book-form-field">
      </div>
      <div class="book-form-field">
        <div class="book-form-field-left">
          <label class="book-form-field-left-label",for='book_room' >メンバー</label>
        </div>
        <div class="book-form-field-right">
          <select name="room[user_ids][]">
            <option value="">ユーザーを選択してください</option>
            <% User.where.not(id: current_user).each do |user|%>
                <option value=<%= user.id %>><%= user.nickname %></option>
            <% end %>
          </select>
          <input name="room[user_ids][]" type="hidden" value=<%= current_user.id%>>
        </div>
      </div>
      <div class="book-form-field">
        <div class="book-form-field-left"></div>
        <div class="book-form-field-right">
          <%= f.submit class: "book-room-form-btn"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render "devise/shared/footer"%>

app/views/talks/index.html.erb
<%= render "devise/shared/header" %>

<div class="talks-wrapper">
  <div class="talk-header">
    <div class="left-header">
      <div class="header-title">
      <%= @room.name %>
      </div>
    </div>
    <div class="right-header">
      <div class="header-button">
        <%= link_to '終了する', room_path(@room), method: :delete %>
      </div>
    </div>
  </div>

  <h2>コメント一覧</h2>

  
  <div class="talks-form">
    <div class="talks-form-sentence">
      <% @talks.each do |talks|%> 
        <div class="takes-mass">
          <div class="upper-talks">
            <div class="talks-name">
              <%= talks.user.nickname%>
            </div>
            <div class="talks-create">
              <%=  talks.created_at.strftime("%Y年%m月%d日 %H時%M分") %>
            </div>
          </div>
          <div class="lower-talks">
            <%= talks.talking%>
          </div>
        </div>
      <% end%>
    </div>
  </div>


  <%= form_with model: [@room, @talk], class: 'form', local: true do |f| %>
    <div class="form-input">
      <%= f.text_field :talking, class: "talk-message", placeholder: "文字を入力してください" %>
    </div>
    <%= f.submit '送信', class: 'form-submit' %>
  <% end %>

</div>

<%= render "devise/shared/footer"%>

app/views/users/show.html.erb
    <%= render "devise/shared/header" %>
    
    <div class="show-wrapper">
      <h2 class="page-heading">ユーザー詳細画面</h2>
        
      <div class="user-show">
        <div class="user-detail">
          ニックネーム
        <%= @user.nickname %>
        </div>


        <div class="user-detail">
          紹介文
        <%= @user.profile %>
        </div>
      </div>

      <div class="book_show_lists">
      <% @books.each do |book| %>
        <li class='list'>
          <%= link_to book_path(book.id)  do %>
          <div class='book-img-view'>
            <%= image_tag book.image.variant(resize: '250x250'), class: "book_image" %>

            <div class='book-information'>
              <div class='book-nickname'>
                <span>タイトル<br> <%= book.title %><br> ジャンル<br>  <%= book.genre.name%></span>
              </div>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>
      </div>
      
    </div>

    <%= render "devise/shared/footer"%>